# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI/CD

on:
  push:
    branches: [ main, development, staging, 'feature/*', 'fix/*' ]
  pull_request:
    branches: [ main, development, staging, 'feature/*', 'fix/*' ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.18.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      - uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: challenge/yarn.lock
      - run: npm install --global yarn
        working-directory: challenge
      - run: yarn install
        working-directory: challenge
      - run: yarn lint --fix
        working-directory: challenge
